CREATE TABLE IF NOT EXISTS casas(
  id_casa int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  city_name VARCHAR ,
  number_rooms int,
  monthly_cost int,
  code int,
  CONSTRAINT client_pkey PRIMARY KEY(id_casa)
);
